### ISSUE TITLE
License

### ISSUE THREAD

**Issue by psyhtest** [amitabhyadav/Shor-Algorithm-on-IBM-Quantum-Experience#1]
Dear @amitabhyadav,

Could you please clarify how your code is licensed? For example, [QISKit](https://www.qiskit.org/) is licensed under [Apache 2.0](https://github.com/QISKit/qiskit-sdk-py/blob/master/LICENSE).

Many thanks!

**Comment by amitabhyadav** [comment]
Thank you for pointing it out. I have updated the project with the MIT License.

**Comment by psyhtest** [comment]
Thank you @amitabhyadav, and good luck with this project!
